module.exports.categoryService=require("./category.service")
module.exports.bookService=require("./book.service")
module.exports.hotelService=require("./hotel.service")
module.exports.stationaryService=require("./stationary.service")
module.exports.userService=require("./user.service")
