module.exports.categoryController=require("./category.controller.js")
module.exports.bookController=require("./book.controller.js")
module.exports.hotelController=require("./hotel.controller.js")
module.exports.stationaryController=require("./stationary.controller.js")
module.exports.userController=require("./user.controller.js")