module.exports.mobileValidation = require("./mobile.validation")
module.exports.cartValidation = require("./cart.validation")
module.exports.orderValidation = require("./order.validation")
module.exports.productValidation = require("./product.validation")
module.exports.userValidation = require("./user.validation")
module.exports.paymentValidation = require("./payment.validation")